version: '3'

services:

  php:
    build: docker
    container_name: "phpfpm"
    volumes:
      - ./docker/webcontent:/var/www/html/
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      #- ./docker/mailer:/etc
    links:
      - mysqldb

  nginx:
    image: nginx:alpine
    container_name: "webserver"
    volumes:
      - ./docker/webcontent:/var/www/html/
      - ./docker/nginx:/etc/nginx/conf.d/
    ports:
      - "8000:80"
    links: 
      - mysqldb
      - php



  mysqldb:
    image: mysql:8.0
    container_name: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
     - "3307:3306"
    volumes:
     - "./docker/sql-data:/var/lib/mysql"
     - "./docker/database.sql:/docker-entrypoint-initdb.d/dump.sql"
    environment:
     - MYSQL_ROOT_PASSWORD=Azerty123




  mailhog:
    image: mailhog/mailhog
    container_name: 'mailhog'
    ports:
      - "1025:1025"
      - "8025:8025"

  nominatim:
    image: mediagis/nominatim:4.1
    container_name: "nominatim"
    ports:
      - "8080:8080"
    environment:
      - PBF_URL=https://download.geofabrik.de/europe/iceland-latest.osm.pbf
      - REPLICATION_URL=https://download.geofabrik.de/europe/iceland-updates/
    volumes:
        - ./docker/nominatim-data:/var/lib/postgresql/12/main
    shm_size: 1gb


